import Reachart from '@/components/Reachart/Reachart';
import React from 'react';
export const metadata = {
  title: "KinKeeper-Stats-Page",
  description: "Generated by create next app",
};
const Stats = () => {
    return (
        <div>
            <Reachart></Reachart>

        </div>
    );
};

export default Stats;