import HandleCall from "@/components/allToggleBtn/HandleCall";
import HandleText from "@/components/allToggleBtn/HandleText";
import HandleVedio from "@/components/allToggleBtn/HandleVedio";
import Image from "next/image";


import { FiArchive } from "react-icons/fi";
import {
  MdAddCall,
  MdDelete,
  MdOutlineDeleteForever,
  MdOutlineNotificationsPaused,
  MdTextsms,
} from "react-icons/md";

export const metadata = {
  title: "KinKeeper-Details-Page",
  description: "Generated by create next app",
};

const frinendDetails = async ({ params }) => {
  const { id } = await params;
  // console.log(data);

  const res = await fetch(
    "https://assingment-7-ken-keeper.vercel.app/Data.json",
    {
      cache: "no-store",
    },
  );
  const friends = await res.json();
  // console.log(friends);

  const friend = friends.find((friend) => friend.id === parseInt(id));
  // console.log(friend);
  if (!friend) {
    return (
      <div className="my-12 max-w-[94%] lg:max-w-[80%] mx-auto">
        <div className="bg-base-300 p-15 lg:p-30 rounded-2xl mt-6 text-black text-4xl font-bold justify-center flex items-center">
          Not Data Found!
        </div>
      </div>
    );
  }
  return (
    <div className="">
      <div className="bg-[#f8fafb] min-h-screen py-20">
        <div className="max-w-7xl mx-auto p-6">
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
            <div className="space-y-4">
              <div className="bg-white rounded-xl shadow p-8 text-center">
                <Image
                  src={friend?.picture}
                  width={1000}
                  height={100}
                  alt="Emma Wilson"
                  className="w-20 h-20 rounded-full mx-auto object-cover"
                />

                <h2 className="text-xl font-bold text-gray-800 mt-4 leading-tight">
                  {friend?.name}
                </h2>

                <div className="flex flex-col items-center gap-2 mt-3">
                  <div className="card-actions">
                    <div
                      className={`badge border-none text-white text-[10px] font-bold py-3.5 px-5 rounded-full uppercase tracking-wider 
                      ${friend?.status === "overdue" ? "bg-[#EF4444]" : ""}
                      ${friend?.status === "tags" ? "bg-[#064E3B]" : ""}
                     
            
            
            `}
                    >
                      {friend?.status}
                    </div>
                  </div>
                  <div className="flex flex-wrap justify-center gap-2 mb-4">
                    {friend?.tags.map((tag, index) => (
                      <div
                        key={index}
                        className="bg-emerald-100 text-emerald-700 text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-wider"
                      >
                        {tag}
                      </div>
                    ))}
                  </div>
                </div>

                <p className="text-gray-400 mt-6 text-sm italic font-medium leading-relaxed">
                  {friend?.bio}
                </p>

                <p className="text-[11px] text-gray-400 mt-3 tracking-wider">
                  Preferred:{" "}
                  <span className="text-gray-500 font-semibold">
                    {friend?.email}
                  </span>
                </p>
              </div>

              <div className="space-y-3">
                <button className="btn shadow rounded-xl w-full bg-white text-gray-700 normal-case font-bold py-6">
                  <MdOutlineNotificationsPaused size={25} /> Snooze 2 Weeks
                </button>

                <button className="btn rounded-xl w-full bg-white shadow text-gray-700 normal-case font-bold py-6">
                  <FiArchive size={20} /> Archive
                </button>

                <button className="btn shadow rounded-xl w-full text-red-500  bg-white normal-case font-bold border-gray-100 hover:text-white hover:bg-red-400 py-6">
                  <MdOutlineDeleteForever size={25} className="" /> Delete
                </button>
              </div>
            </div>

            <div className="lg:col-span-3 space-y-6">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
                <div className="bg-white rounded-xl shadow p-8 text-center">
                  <h2 className="text-4xl font-bold text-[#1a4d40]">
                    {friend?.days_since_contact}
                  </h2>
                  <p className="text-gray-400 text-sm mt-3 font-medium">
                    Days Since Contact
                  </p>
                </div>

                <div className="bg-white rounded-xl shadow p-8 text-center">
                  <h2 className="text-4xl font-bold text-[#1a4d40]">
                    {friend?.goal}
                  </h2>
                  <p className="text-gray-400 text-sm mt-3 font-medium">
                    Goal (Days)
                  </p>
                </div>

                <div className="bg-white rounded-2xl shadow p-8 text-center">
                  <h2 className="text-3xl font-bold text-[#1a4d40]">
                    {/* {friend?.next_due_date} */}
                    {friend?.next_due_date}
                  </h2>
                  <p className="text-gray-400 text-sm mt-3 font-medium">
                    Next Due
                  </p>
                </div>
              </div>

              <div className="bg-white rounded-2xl shadow p-8 flex justify-between items-center">
                <div>
                  <h2 className="text-lg font-bold text-[#1a4d40]">
                    Relationship Goal
                  </h2>
                  <p className="text-gray-500 mt-2 text-base">
                    Connect every{" "}
                    <span className="font-bold text-gray-800">30 days</span>
                  </p>
                </div>

                <button className="btn btn-ghost border border-gray-200 btn-sm normal-case font-bold text-gray-500 bg-[#fbfcfc]">
                  Edit
                </button>
              </div>

              <div className="bg-white rounded-xl shadow p-8">
                <h2 className="text-lg font-bold text-[#1a4d40] mb-8">
                  Quick Check-In
                </h2>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
                  <HandleCall friend={friend}></HandleCall>

                  <HandleText friend={friend}></HandleText>

                  <HandleVedio friend={friend}></HandleVedio>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default frinendDetails;
